# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x05tofnd\"[\n\x12KeyPresenceRequest\x12\x0f\n\x07key_uid\x18\x01 \x01(\t\x12\x0f\n\x07pub_key\x18\x02 \x01(\x0c\x12#\n\talgorithm\x18\x03 \x01(\x0e\x32\x10.tofnd.Algorithm\"\xb0\x01\n\x13KeyPresenceResponse\x12\x35\n\x08response\x18\x01 \x01(\x0e\x32#.tofnd.KeyPresenceResponse.Response\"b\n\x08Response\x12\x18\n\x14RESPONSE_UNSPECIFIED\x10\x00\x12\x14\n\x10RESPONSE_PRESENT\x10\x01\x12\x13\n\x0fRESPONSE_ABSENT\x10\x02\x12\x11\n\rRESPONSE_FAIL\x10\x03*7\n\tAlgorithm\x12\x13\n\x0f\x41LGORITHM_ECDSA\x10\x00\x12\x15\n\x11\x41LGORITHM_ED25519\x10\x01\x42\rZ\x0btofnd;tofndb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013tofnd;tofnd'
  _globals['_ALGORITHM']._serialized_start=295
  _globals['_ALGORITHM']._serialized_end=350
  _globals['_KEYPRESENCEREQUEST']._serialized_start=23
  _globals['_KEYPRESENCEREQUEST']._serialized_end=114
  _globals['_KEYPRESENCERESPONSE']._serialized_start=117
  _globals['_KEYPRESENCERESPONSE']._serialized_end=293
  _globals['_KEYPRESENCERESPONSE_RESPONSE']._serialized_start=195
  _globals['_KEYPRESENCERESPONSE_RESPONSE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
