# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import multisig_pb2 as multisig__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in multisig_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MultisigStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.KeyPresence = channel.unary_unary(
                '/tofnd.Multisig/KeyPresence',
                request_serializer=common__pb2.KeyPresenceRequest.SerializeToString,
                response_deserializer=common__pb2.KeyPresenceResponse.FromString,
                _registered_method=True)
        self.Keygen = channel.unary_unary(
                '/tofnd.Multisig/Keygen',
                request_serializer=multisig__pb2.KeygenRequest.SerializeToString,
                response_deserializer=multisig__pb2.KeygenResponse.FromString,
                _registered_method=True)
        self.Sign = channel.unary_unary(
                '/tofnd.Multisig/Sign',
                request_serializer=multisig__pb2.SignRequest.SerializeToString,
                response_deserializer=multisig__pb2.SignResponse.FromString,
                _registered_method=True)


class MultisigServicer(object):
    """Missing associated documentation comment in .proto file."""

    def KeyPresence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Keygen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultisigServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'KeyPresence': grpc.unary_unary_rpc_method_handler(
                    servicer.KeyPresence,
                    request_deserializer=common__pb2.KeyPresenceRequest.FromString,
                    response_serializer=common__pb2.KeyPresenceResponse.SerializeToString,
            ),
            'Keygen': grpc.unary_unary_rpc_method_handler(
                    servicer.Keygen,
                    request_deserializer=multisig__pb2.KeygenRequest.FromString,
                    response_serializer=multisig__pb2.KeygenResponse.SerializeToString,
            ),
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=multisig__pb2.SignRequest.FromString,
                    response_serializer=multisig__pb2.SignResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tofnd.Multisig', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tofnd.Multisig', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Multisig(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def KeyPresence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tofnd.Multisig/KeyPresence',
            common__pb2.KeyPresenceRequest.SerializeToString,
            common__pb2.KeyPresenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Keygen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tofnd.Multisig/Keygen',
            multisig__pb2.KeygenRequest.SerializeToString,
            multisig__pb2.KeygenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tofnd.Multisig/Sign',
            multisig__pb2.SignRequest.SerializeToString,
            multisig__pb2.SignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
