# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multisig.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'multisig.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emultisig.proto\x12\x05tofnd\x1a\x0c\x63ommon.proto\"X\n\rKeygenRequest\x12\x0f\n\x07key_uid\x18\x01 \x01(\t\x12\x11\n\tparty_uid\x18\x02 \x01(\t\x12#\n\talgorithm\x18\x03 \x01(\x0e\x32\x10.tofnd.Algorithm\"G\n\x0eKeygenResponse\x12\x11\n\x07pub_key\x18\x01 \x01(\x0cH\x00\x12\x0f\n\x05\x65rror\x18\x02 \x01(\tH\x00\x42\x11\n\x0fkeygen_response\"|\n\x0bSignRequest\x12\x0f\n\x07key_uid\x18\x01 \x01(\t\x12\x13\n\x0bmsg_to_sign\x18\x02 \x01(\x0c\x12\x11\n\tparty_uid\x18\x03 \x01(\t\x12\x0f\n\x07pub_key\x18\x04 \x01(\x0c\x12#\n\talgorithm\x18\x05 \x01(\x0e\x32\x10.tofnd.Algorithm\"E\n\x0cSignResponse\x12\x13\n\tsignature\x18\x01 \x01(\x0cH\x00\x12\x0f\n\x05\x65rror\x18\x02 \x01(\tH\x00\x42\x0f\n\rsign_response2\xb8\x01\n\x08Multisig\x12\x44\n\x0bKeyPresence\x12\x19.tofnd.KeyPresenceRequest\x1a\x1a.tofnd.KeyPresenceResponse\x12\x35\n\x06Keygen\x12\x14.tofnd.KeygenRequest\x1a\x15.tofnd.KeygenResponse\x12/\n\x04Sign\x12\x12.tofnd.SignRequest\x1a\x13.tofnd.SignResponseB\rZ\x0btofnd;tofndb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multisig_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013tofnd;tofnd'
  _globals['_KEYGENREQUEST']._serialized_start=39
  _globals['_KEYGENREQUEST']._serialized_end=127
  _globals['_KEYGENRESPONSE']._serialized_start=129
  _globals['_KEYGENRESPONSE']._serialized_end=200
  _globals['_SIGNREQUEST']._serialized_start=202
  _globals['_SIGNREQUEST']._serialized_end=326
  _globals['_SIGNRESPONSE']._serialized_start=328
  _globals['_SIGNRESPONSE']._serialized_end=397
  _globals['_MULTISIG']._serialized_start=400
  _globals['_MULTISIG']._serialized_end=584
# @@protoc_insertion_point(module_scope)
